### PR TITLE
Previous pull request

### PR DESCRIPTION
**Pull request by Joanguitar**
This is #18 built on top of #19.
I also included a simple script to tune the threshold for pocket-sphinx word detection.

### CODE REVIEW

**Comment by JarbasAl** [comment]
please rebase

**Comment by Joanguitar** [comment]
The new changes you implemented are not based in the master branches of the OVOS plugins.
It's hard to keep track of what versions of each plugin this code is supposed to work with.

**Comment by JarbasAl** [comment]
everything is based on the latest versions on github, the versions on pip usually lag behind for some time

**Comment by Joanguitar** [comment]
I'm using the last versions on Github and [OVOS-plugin-manager](https://github.com/OpenVoiceOS/OVOS-plugin-manager) doesn't have [OVOSWakeWordFactory](https://github.com/JarbasHiveMind/HiveMind-voice-sat/blob/master/mycroft_voice_satellite/speech/listener.py#L29) in [wakewords](https://github.com/OpenVoiceOS/OVOS-plugin-manager/blob/master/ovos_plugin_manager/wakewords.py).

**Comment by JarbasAl** [comment]
oops, you are right, that comes in https://github.com/OpenVoiceOS/OVOS-plugin-manager/pull/3

**Comment by Joanguitar** [comment]
Wonderful, after a few changes on how the configuration for the STT and the TTS is loaded it's finally working.

**Comment by Joanguitar** [comment]
I guess many of the scripts inside the folder "useful_scripts" are not that useful, like the ones corresponding to the HiveMind server that may not be that interesting or they may fit better a different repository, so please tell me the ones you want to keep.

**Comment by JarbasAl** [comment]
deprecated by #21

**Pull request closed without merging**
